FLAG_EVENT_CODES = {
    "event_defeat_wake",
    "event_met_oak_at_palpark",
    "event_clear_lakeverity",
    "event_learn_of_lake_explosion",
    "event_defeat_gardenia",
    "event_defeat_maylene",
    "event_galactic_hq_defeat_cyrus",
    "event_clear_lakevalor",
    "event_clear_lakeacuity",
    "event_defeat_candice",
    "event_clear_eternahideout",
    "event_defeat_fantina",
    "event_defeat_roark",
    "event_defeat_volkner",
    "event_defeat_byron",
    "event_defeat_cynthia",
    "event_clear_distortion",
    "event_clear_windworks",
    "event_clear_starkmountain",
}

FLAG_ITEM1_CODES = {
  {option="opt_overworld_off", codes={"reapercloth"}},
  {option="opt_badges_off", codes={"minebadge"}},
  {option="opt_hms_off", codes={"hm03surf"}},
  {option="opt_hidden_off", codes={"kingsrock"}},
  {option="opt_bicycle_off", codes={"bicycle"}},
  {option="opt_badges_off", codes={"forestbadge"}},
  {option="opt_hms_off", codes={"hm01cut"}},
  {option="opt_hidden_off", codes={"moonstone"}},
  {option="opt_npcgifts_off", codes={"upgrade"}},
  {option="opt_overworld_off", codes={"tm95doublehit"}},
  {option="opt_rods_off", codes={"superrod"}},
  {option="opt_overworld_off", codes={"leafstone"}},
  {option="opt_keyitems_off", codes={"workskey"}},
  {option="opt_overworld_off", codes={"firestone"}},
  {option="opt_overworld_off", codes={"tm93rollout"}},
  {option="opt_overworld_off", codes={"dubiousdisc"}},
  {option="opt_hidden_off", codes={"razorclaw"}},
  {option="opt_keyitems_off", codes={"linkingcord"}},
  {option="opt_keyitems_off", codes={"galactickey"}},
  {option="opt_hidden_off", codes={"leafstone"}},
  {option="opt_badges_off", codes={"relicbadge"}},
  {option="opt_hidden_off", codes={"poffincase"}},
  {option="opt_overworld_off", codes={"protector"}},
  {option="opt_overworld_off", codes={"shinystone"}},
  {option="opt_hms_off", codes={"hm04strength"}},
  {option="opt_npcgifts_off", codes={"metalcoat"}},
  {option="opt_overworld_off", codes={"metalcoat"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_cartridges_off", codes={"fireredcartridge"}},
  {option="opt_cartridges_off", codes={"leafgreencartridge"}},
}

FLAG_ITEM2_CODES = {
  {option="opt_poketchapps_off", codes={"poketch"}},
  {option="opt_cartridges_off", codes={"sapphirecartridge"}},
  {option="opt_overworld_off", codes={"dawnstone"}},
  {option="opt_hidden_off", codes={"sunstone"}},
  {option="opt_hidden_off", codes={"moonstone"}},
  {option="opt_overworld_off", codes={"tm96mimic"}},
  {option="opt_badges_off", codes={"coalbadge"}},
  {option="opt_hms_off", codes={"hm06rocksmash"}},
  {option="opt_hms_off", codes={"tm70flash"}},
  {option="opt_cartridges_off", codes={"emeraldcartridge"}},
  {option="opt_badges_off", codes={"fenbadge"}},
  {option="{}", codes={""}},
  {option="opt_poketchapps_off", codes={"markingmap"}},
  {option="opt_poketchapps_off", codes={"dowsingmachine"}},
  {option="opt_npcgifts_off", codes={"oddkeystone"}},
  {option="opt_rods_off", codes={"goodrod"}},
  {option="opt_overworld_off", codes={"ovalstone"}},
  {option="opt_hidden_off", codes={"shinystone"}},
  {option="opt_keyitems_off", codes={"oldcharm"}},
  {option="opt_hidden_off", codes={"dawnstone"}},
  {option="opt_keyitems_off", codes={"suitekey"}},
  {option="opt_overworld_off", codes={"waterstone"}},
  {option="opt_overworld_off", codes={"magmarizer"}},
  {option="opt_hidden_off", codes={"razorfang"}},
  {option="opt_hms_off", codes={"hm08rockclimb"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_rods_off", codes={"oldrod"}},
  {option="opt_overworld_off", codes={"razorclaw"}},
  {option="opt_overworld_off", codes={"upgrade"}},
  {option="opt_overworld_off", codes={"dawnstone"}},
  {option="opt_overworld_off", codes={"dubiousdisc"}},
  {option="opt_hidden_off", codes={"leafstone"}},
}

FLAG_ITEM3_CODES = {
  {option="opt_overworld_off", codes={"razorfang"}},
  {option="opt_overworld_off", codes={"protector"}},
  {option="opt_overworld_off", codes={"shinystone"}},
  {option="opt_overworld_off", codes={"reapercloth"}},
  {option="opt_hidden_off", codes={"thunderstone"}},
  {option="opt_hidden_off", codes={"waterstone"}},
  {option="opt_keyitems_off", codes={"pokeradar"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_badges_off", codes={"iciclebadge"}},
  {option="opt_overworld_off", codes={"tm94ancientpower"}},
  {option="opt_hidden_off", codes={"firestone"}},
  {option="opt_hidden_off", codes={"waterstone"}},
  {option="opt_hidden_off", codes={"thunderstone"}},
  {option="opt_hms_off", codes={"hm05defog"}},
  {option="opt_timeitems_off", codes={"nighttime"}},
  {option="opt_hidden_off", codes={"firestone"}},
  {option="opt_badges_off", codes={"beaconbadge"}},
  {option="opt_hms_off", codes={"hm07waterfall"}},
  {option="opt_overworld_off", codes={"thunderstone"}},
  {option="opt_overworld_off", codes={"upgrade"}},
  {option="opt_hidden_off", codes={"oddkeystone"}},
  {option="opt_keyitems_off", codes={"parcel"}},
  {option="opt_ssticket_off", codes={"ssticket"}},
  {option="opt_bag_off", codes={"bag"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
}

FLAG_ITEM4_CODES = {
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_cartridges_off", codes={"rubycartridge"}},
  {option="opt_overworld_off", codes={"electirizer"}},
  {option="opt_keyitems_off", codes={"secretpotion"}},
  {option="opt_hidden_off", codes={"sunstone"}},
  {option="opt_overworld_off", codes={"duskstone"}},
  {option="opt_hms_off", codes={"hm02fly"}},
  {option="opt_badges_off", codes={"cobblebadge"}},
  {option="opt_overworld_off", codes={"razorclaw"}},
  {option="opt_overworld_off", codes={"duskstone"}},
  {option="opt_timeitems_off", codes={"daytime"}},
  {option="opt_hidden_off", codes={"duskstone"}},
}