FLAG_EVENT_CODES = {
    "event_defeat_wake",
    "event_met_oak_at_palpark",
    "event_clear_lakeverity",
    "event_learn_of_lake_explosion",
    "event_defeat_gardenia",
    "event_defeat_maylene",
    "event_galactic_hq_defeat_cyrus",
    "event_clear_lakevalor",
    "event_clear_lakeacuity",
    "event_defeat_candice",
    "event_clear_eternahideout",
    "event_defeat_fantina",
    "event_defeat_roark",
    "event_defeat_volkner",
    "event_defeat_byron",
    "event_defeat_cynthia",
    "event_clear_distortion",
    "event_clear_windworks",
    "event_clear_starkmountain",
    "event_roamer_1",
    "event_roamer_0",
    "event_roamer_3"
}

FLAG_ITEM1_CODES = {
  {option="opt_badges_off", codes={"minebadge"}},
  {option="opt_hms_off", codes={"hm03surf"}},
  {option="opt_bicycle_off", codes={"bicycle"}},
  {option="opt_badges_off", codes={"forestbadge"}},
  {option="opt_hms_off", codes={"hm01cut"}},
  {option="opt_rods_off", codes={"superrod"}},
  {option="opt_keyitems_off", codes={"workskey"}},
  {option="opt_keyitems_off", codes={"galactickey"}},
  {option="opt_badges_off", codes={"relicbadge"}},
  {option="opt_hms_off", codes={"hm04strength"}},
  {option="opt_coupons_off", codes={"coupon_1"}},
  {option="opt_coupons_off", codes={"coupon_2"}},
  {option="opt_coupons_off", codes={"coupon_3"}},
  {option="opt_poketchapps_off", codes={"poketch"}},
  {option="opt_badges_off", codes={"coalbadge"}},
  {option="opt_hms_off", codes={"hm06rocksmash"}},
  {option="opt_hms_off", codes={"tm70flash"}},
  {option="opt_badges_off", codes={"fenbadge"}},
  {option="opt_poketchapps_off", codes={"dowsingmachine"}},
  {option="opt_rods_off", codes={"goodrod"}},
  {option="opt_keyitems_off", codes={"oldcharm"}},
  {option="opt_keyitems_off", codes={"suitekey"}},
  {option="opt_hms_off", codes={"hm08rockclimb"}},
  {option="opt_pokedex_off", codes={"pokedex_2"}},
  {option="opt_rods_off", codes={"oldrod"}},
  {option="opt_pokedex_off", codes={"pokedex_1"}},
  {option="opt_pokedex_off", codes={"pokedex_3"}},
  {option="opt_badges_off", codes={"iciclebadge"}},
  {option="opt_hms_off", codes={"hm05defog"}},
  {option="opt_badges_off", codes={"beaconbadge"}},
  {option="opt_hms_off", codes={"hm07waterfall"}},
  {option="opt_keyitems_off", codes={"parcel"}},
}

FLAG_ITEM2_CODES = {
  {option="opt_hidden_off", codes={"unownfile_a"}},
  {option="opt_hidden_off", codes={"unownfile_b"}},
  {option="opt_hidden_off", codes={"unownfile_c"}},
  {option="opt_hidden_off", codes={"unownfile_d"}},
  {option="opt_hidden_off", codes={"unownfile_e"}},
  {option="opt_hidden_off", codes={"unownfile_ex"}},
  {option="opt_hidden_off", codes={"unownfile_f"}},
  {option="opt_hidden_off", codes={"unownfile_g"}},
  {option="opt_hidden_off", codes={"unownfile_h"}},
  {option="opt_hidden_off", codes={"unownfile_i"}},
  {option="opt_hidden_off", codes={"unownfile_j"}},
  {option="opt_hidden_off", codes={"unownfile_k"}},
  {option="opt_hidden_off", codes={"unownfile_l"}},
  {option="opt_hidden_off", codes={"unownfile_m"}},
  {option="opt_hidden_off", codes={"unownfile_n"}},
  {option="opt_hidden_off", codes={"unownfile_o"}},
  {option="opt_hidden_off", codes={"unownfile_p"}},
  {option="opt_hidden_off", codes={"unownfile_q"}},
  {option="opt_hidden_off", codes={"unownfile_qu"}},
  {option="opt_hidden_off", codes={"unownfile_r"}},
  {option="opt_hidden_off", codes={"unownfile_s"}},
  {option="opt_hidden_off", codes={"unownfile_t"}},
  {option="opt_hidden_off", codes={"unownfile_u"}},
  {option="opt_hidden_off", codes={"unownfile_v"}},
  {option="opt_hidden_off", codes={"unownfile_w"}},
  {option="opt_hidden_off", codes={"unownfile_x"}},
  {option="opt_hidden_off", codes={"unownfile_y"}},
  {option="opt_hidden_off", codes={"unownfile_z"}},
  {option="opt_keyitems_off", codes={"secretpotion"}},
  {option="opt_hms_off", codes={"hm02fly"}},
  {option="opt_badges_off", codes={"cobblebadge"}},
}

UNOWN_ITEMS = {
    "unownfile_a", "unownfile_b", "unownfile_c", "unownfile_d",
    "unownfile_e", "unownfile_ex", "unownfile_f", "unownfile_g",
    "unownfile_h", "unownfile_i", "unownfile_j", "unownfile_k",
    "unownfile_l", "unownfile_m", "unownfile_n", "unownfile_o",
    "unownfile_p", "unownfile_q", "unownfile_qu", "unownfile_r",
    "unownfile_s", "unownfile_t", "unownfile_u", "unownfile_v",
    "unownfile_w", "unownfile_x", "unownfile_y", "unownfile_z"
}
