FLAG_EVENT_CODES = {
    "event_defeat_wake",
    "event_met_oak_at_palpark",
    "event_clear_lakeverity",
    "event_learn_of_lake_explosion",
    "event_defeat_gardenia",
    "event_defeat_maylene",
    "event_galactic_hq_defeat_cyrus",
    "event_clear_lakevalor",
    "event_clear_lakeacuity",
    "event_defeat_candice",
    "event_clear_eternahideout",
    "event_defeat_fantina",
    "event_defeat_roark",
    "event_defeat_volkner",
    "event_defeat_byron",
    "event_defeat_cynthia",
    "event_clear_distortion",
    "event_clear_windworks",
}

FLAG_ITEM1_CODES = {
  {option="opt_badges_off", codes={"minebadge"}},
  {option="opt_hms_off", codes={"hm03surf"}},
  {option="opt_bicycle_off", codes={"bicycle"}},
  {option="opt_badges_off", codes={"forestbadge"}},
  {option="opt_hms_off", codes={"hm01cut"}},
  {option="opt_rods_off", codes={"superrod"}},
  {option="opt_keyitems_off", codes={"workskey"}},
  {option="opt_keyitems_off", codes={"galactickey"}},
  {option="opt_badges_off", codes={"relicbadge"}},
  {option="opt_hms_off", codes={"hm04strength"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_coupons_off", codes={"coupons"}},
  {option="opt_poketchapps_off", codes={"poketch"}},
  {option="opt_badges_off", codes={"coalbadge"}},
  {option="opt_hms_off", codes={"hm06rocksmash"}},
  {option="opt_hms_off", codes={"tm70flash"}},
  {option="opt_badges_off", codes={"fenbadge"}},
  {option="opt_poketchapps_off", codes={"dowsingmachine"}},
  {option="opt_rods_off", codes={"goodrod"}},
  {option="opt_keyitems_off", codes={"oldcharm"}},
  {option="opt_keyitems_off", codes={"suitekey"}},
  {option="opt_hms_off", codes={"hm08rockclimb"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_rods_off", codes={"oldrod"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_pokedex_off", codes={"pokedex"}},
  {option="opt_badges_off", codes={"iciclebadge"}},
  {option="opt_hms_off", codes={"hm05defog"}},
  {option="opt_badges_off", codes={"beaconbadge"}},
  {option="opt_hms_off", codes={"hm07waterfall"}},
  {option="opt_keyitems_off", codes={"parcel"}},
}

FLAG_ITEM2_CODES = {
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_hidden_off", codes={"unownfile"}},
  {option="opt_keyitems_off", codes={"secretpotion"}},
  {option="opt_hms_off", codes={"hm02fly"}},
  {option="opt_badges_off", codes={"cobblebadge"}},
}